/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC14_Group_02_Assignment_2;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    private App app;

    @BeforeEach
    void init() {
        app = new App();
        assertNotNull(app);
    }

    @Test
    public void testInvalidStringToFile() {
        String filename = "";
        assertNotNull(App.getFile(filename));
    }

    @Test
    public void testValidStringToFile() {
        String filename = "../app/src/main/resources/Databases/ProductDatabase.json";
        assertNotNull(App.getFile(filename));
    }

}
